apiVersion: v1
kind: PersistentVolume
metadata:
  name: rtm-db-pv
  namespace: rtm-client-environment
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/chatbot_database
